version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db

    container_name: popeye-back

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    container_name: popeye-front

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: popeye-db